name: Build

on:
  push:
    branches: [ main, master, develop ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ main, master, develop ]
    paths-ignore:
      - 'docs/**'

jobs:
  unix:
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    timeout-minutes: 45

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    env:
      DISPLAY: ":99.0"
      # MARKTEXT_IS_STABLE: 1
      MARKTEXT_EXIT_ON_ERROR: 1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
          cache: npm

      - name: Install build dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get -y update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Cache node_modules
        uses: actions/cache@v4
        id: cacheNodeModules
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node_modules-v1-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-v1-

      - name: Cache Rust
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install dependencies
        if: steps.cacheNodeModules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Lint
        run: |
          npm run lint
          npm run validate-licenses

      - name: Run unit and E2E tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test

      - name: Build
        run: npm run build

  windows:
    runs-on: windows-latest
    continue-on-error: false
    timeout-minutes: 45

    env:
      # MARKTEXT_IS_STABLE: 1
      MARKTEXT_EXIT_ON_ERROR: 1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
          cache: npm

      - name: Cache node_modules
        uses: actions/cache@v4
        id: cacheNodeModules
        with:
          path: ${{ github.workspace }}\node_modules
          key: ${{ runner.os }}-node_modules-v1-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-v1-

      - name: Cache Rust
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install dependencies
        if: steps.cacheNodeModules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Lint
        run: |
          npm run lint
          npm run validate-licenses

      - name: Run unit and E2E tests
        run: npm run test

      - name: Build
        run: npm run build
