name: Release

on:
  push:
    branches:
      - 'release-v*'

jobs:
  unix:
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    timeout-minutes: 45

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    env:
      DISPLAY: ":99.0"
      MARKTEXT_IS_STABLE: 1
      MARKTEXT_EXIT_ON_ERROR: 1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
          cache: npm

      - name: Install build dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get -y update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node_modules-release-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-release-

      - name: Cache Rust
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: |
          npm run lint
          npm run validate-licenses

      - name: Run unit and E2E tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test

      - name: Build
        run: npm run build:installer-release

      - name: Calculate checksums
        if: runner.os == 'Linux'
        run: |
          find src-tauri/target/release/bundle -type f \( -name "*.deb" -o -name "*.rpm" -o -name "*.AppImage" -o -name "*.tar.gz" \) -exec sha256sum {} \;
        shell: bash

      - name: Calculate checksums
        if: runner.os == 'macOS'
        run: |
          find src-tauri/target/release/bundle -type f \( -name "*.dmg" -o -name "*.zip" \) -exec shasum -a 256 {} \;
        shell: bash

  windows:
    runs-on: windows-latest
    continue-on-error: false
    timeout-minutes: 45

    env:
      MARKTEXT_IS_STABLE: 1
      MARKTEXT_EXIT_ON_ERROR: 1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
          cache: npm

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}\node_modules
          key: ${{ runner.os }}-node_modules-release-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-release-

      - name: Cache Rust
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: |
          npm run lint
          npm run validate-licenses

      - name: Run unit and E2E tests
        run: npm run test

      - name: Build
        run: npm run build:installer-release

      - name: Calculate checksums
        run: |
          Get-ChildItem -Path "src-tauri\target\release\bundle" -Recurse -Include "*.exe","*.msi" | ForEach-Object {
            $hash = (Get-FileHash -Algorithm SHA256 $_.FullName).Hash
            Write-Host "$hash  $($_.Name)"
          }
        shell: pwsh
